language: python
python:
  - "2.7"
cache: pip
install: pip install -r requirements.txt
script: 
  - find testdecks/ -name "*.txt" -print0 | xargs -0 python StackIt.py
  - find testdecks/ -name "*.dec" -print0 | xargs -0 python StackIt.py
  - find testdecks/ -name "*.dek" -print0 | xargs -0 python StackIt.py
